Fix MSVC errors related to math.
MSVC requires `-D_USE_MATH_DEFINES=1` in order to be standards-conforming.
https://stackoverflow.com/questions/6563810/m-pi-works-with-math-h-but-not-with-cmath-in-visual-studio

   util.cpp(197): error C2065: 'M_PI': undeclared identifier

MSVC warns on implicit double-to-float conversions:

   screenshot.cpp(825): warning C4305: 'argument': truncation from 'double' to 'float'
   screenshot.cpp(827): warning C4305: 'argument': truncation from 'double' to 'float'
   screenshot.cpp(829): warning C4305: 'argument': truncation from 'double' to 'float'