Fix a typo-bug in f20a6bf2: s/phtread/pthread/
However, this does not unbreak the build on Emscripten.
Emscripten doesn't know where to find <zlib.h> at all:

    ./sysconfig.h:429:10: fatal error: 'zlib.h' file not found
    #include <zlib.h>
             ^~~~~~~~