Only apply -std=c++11 to C++ flags
CPPFLAGS are applied to both .cpp and .c files, and that breaks clang build:

error: invalid argument '-std=c++11' not allowed with 'C/ObjC'